#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the whatFlavors function below.
def whatFlavors(cost, money):
    seen={}
    for j,i in enumerate(cost):
        if money-i in seen:
            print(seen[money-i],j+1)
            return 
        else:
            seen[i]=j+1
if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        money = int(input())

        n = int(input())

        cost = list(map(int, input().rstrip().split()))

        whatFlavors(cost, money)
