#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the isBalanced function below.
def isBalanced(s):
    stack=[]
    temp={'}':'{',']':'[',')':'('}
    for i in s:
        if i in temp.values():
            stack.append(i)
        else:
            if len(stack)>0 and stack[-1]==temp[i]:
                stack.pop(-1)
            else:
                stack.append(i)
    if stack==[]:
        return 'YES'
    return 'NO'
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
