#!/bin/python3

import sys

def lowestTriangle(b, a):
    return int(2 * a / b + bool((2 * a) % b))

base, area = input().strip().split(' ')
base, area = [int(base), int(area)]
height = lowestTriangle(base, area)
print(height)
