#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    temp=s[2:-2]
    if s[-2]=='P':
        if s[0:2]=='12':
            return s[0:-2]
        ans=str(12+int(s[0:2]))
        ans+=temp
    else:
        ans=str(12-int(s[0:2]))
        if int(ans)==0:
            ans=f'0{ans}'
            ans+=temp
        else:
            return s[0:-2]
    return ans

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
