#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    ans_apple,ans_orange=0,0
    for apple in apples:
        if apple+a<=t and apple+a>=s:
            ans_apple+=1
    for orange in oranges:
        if orange+b<=t and orange+b>=s:
            ans_orange+=1
    print(ans_apple)
    print(ans_orange)
if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
